basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Peerdrive API
  version: "1.0"
paths:
  /ping:
    get:
      description: Returns a pong message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping the server
      tags:
      - health
swagger: "2.0"
