// Package model defines data structures for collection management and version control.
// Collection (collections table): a set of named path→hash mappings owned by a user.
//   CurrentHash field: points to the SHA256 of the AnonCollection JSON generated by the current commit.
//   Updated with a new hash on each Commit; also updated on rollback.
//   GetCollection preferentially returns content via CurrentHash, falling back to the collection_entries table.
// CollectionEntry (collection_entries table): a single path mapping within a collection (workspace).
// CollectionVersion (collection_versions table): entry snapshot at commit time,
//   forming a version chain through parent_version_id.
// VersionEntry (version_entries table): a single entry record within a version snapshot.

package model

import (
	"database/sql"
	"encoding/json"
)

type Collection struct {
	ID              int      `db:"id" json:"id"`
	Username        string   `db:"username" json:"username"`
	CollectionName  string   `db:"collection_name" json:"collection_name"`
	CurrentHash     *string  `db:"current_hash" json:"current_hash"`
	Visibility      string   `db:"visibility" json:"visibility"`
	FollowRedirects bool     `db:"follow_redirects" json:"follow_redirects"`
	Tags            []string `db:"tags" json:"tags"`
	CreatedAt       string   `db:"created_at" json:"created_at"`
}

type collectionRow struct {
	ID              int
	Username        string
	CollectionName  string
	CurrentHash     *string
	Visibility      string
	FollowRedirects bool
	Tags            sql.NullString
	CreatedAt       string
}

// ScanRow reads collection fields from a database scanner and populates the Collection struct.
func (c *Collection) ScanRow(s Scanner, columns ...string) error {
	var r collectionRow
	if err := s.Scan(&r.ID, &r.Username, &r.CollectionName, &r.CurrentHash,
		&r.Visibility, &r.FollowRedirects, &r.Tags, &r.CreatedAt); err != nil {
		return err
	}
	c.ID = r.ID
	c.Username = r.Username
	c.CollectionName = r.CollectionName
	c.CurrentHash = r.CurrentHash
	c.Visibility = r.Visibility
	c.FollowRedirects = r.FollowRedirects
	c.CreatedAt = r.CreatedAt
	if r.Tags.Valid && r.Tags.String != "" {
		json.Unmarshal([]byte(r.Tags.String), &c.Tags)
	}
	if c.Tags == nil {
		c.Tags = []string{}
	}
	return nil
}

type Scanner interface {
	Scan(...interface{}) error
}

// ScanCollection reads a collection record from a database row scanner and returns a Collection pointer.
func ScanCollection(scanner interface{ Scan(...interface{}) error }) (*Collection, error) {
	var c Collection
	var tagsStr sql.NullString
	err := scanner.Scan(&c.ID, &c.Username, &c.CollectionName, &c.CurrentHash, &c.Visibility, &c.FollowRedirects, &tagsStr, &c.CreatedAt)
	if err != nil {
		return nil, err
	}
	if tagsStr.Valid && tagsStr.String != "" {
		json.Unmarshal([]byte(tagsStr.String), &c.Tags)
	}
	if c.Tags == nil {
		c.Tags = []string{}
	}
	return &c, nil
}

// MarshalTags serializes a slice of tag strings to a JSON string; returns an empty string when the input is nil.
func MarshalTags(tags []string) string {
	if tags == nil {
		return ""
	}
	data, _ := json.Marshal(tags)
	return string(data)
}

type CollectionEntry struct {
	ID            int    `db:"id" json:"id"`
	CollectionID  int    `db:"collection_id" json:"collection_id"`
	Path          string `db:"path" json:"path"`
	FileHash      string `db:"file_hash" json:"file_hash"`
	ProvidersJSON string `db:"providers_json" json:"-"`
}

// BuildProviders reconstructs the full providers array from file_hash and providers_json.
func (e *CollectionEntry) BuildProviders() []Provider {
	if e.ProvidersJSON != "" {
		var providers []Provider
		if err := json.Unmarshal([]byte(e.ProvidersJSON), &providers); err == nil && len(providers) > 0 {
			return providers
		}
	}
	if e.FileHash != "" {
		return []Provider{{Type: "sha256", Value: e.FileHash}}
	}
	return []Provider{}
}

type CollectionVersion struct {
	ID              int    `db:"id" json:"id"`
	CollectionID    int    `db:"collection_id" json:"collection_id"`
	VersionNumber   int    `db:"version_number" json:"version_number"`
	CommitMessage   string `db:"commit_message" json:"commit_message"`
	CreatedAt       string `db:"created_at" json:"created_at"`
	ParentVersionID *int   `db:"parent_version_id" json:"parent_version_id"`
}

type VersionEntry struct {
	ID            int    `db:"id" json:"id"`
	VersionID     int    `db:"version_id" json:"version_id"`
	Path          string `db:"path" json:"path"`
	FileHash      string `db:"file_hash" json:"file_hash"`
	ProvidersJSON string `db:"providers_json" json:"-"`
}
